tap "ethereum/ethereum"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "asdf"
brew "bash"
brew "bat"
brew "direnv"
brew "entr"
brew "ethereum"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "glow"
brew "gnupg"
brew "go"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "macos-trash"
brew "mas"
brew "navi"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "newsboat"
brew "ngrep"
brew "pastel"
brew "ripgrep"
brew "sloccount"
brew "solidity"
brew "starship"
brew "stow"
brew "terminal-notifier"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "wtfutil"
brew "zoxide"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "alacritty", args: { appdir: "~/Applications" }
cask "brave-browser", args: { appdir: "~/Applications" }
cask "discord", args: { appdir: "~/Applications" }
cask "docker", args: { appdir: "~/Applications" }
cask "font-hack-nerd-font"
cask "graphql-playground", args: { appdir: "~/Applications" }
cask "postman", args: { appdir: "~/Applications" }
cask "rectangle", args: { appdir: "~/Applications" }
mas "Alfred", id: 405843582
mas "Fantastical", id: 975937182
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
